### ISSUE TITLE
maximumResultsReached - get_everything method

### ISSUE THREAD

**Issue by Deadshot20** [mattlisiv/newsapi-python#39]
I have been trying to get all the news article related to say money laundering using the **get_everything** method, but after a certain number of results have been accessed, it gives up this error.

![image](https://user-images.githubusercontent.com/7498849/60561527-73bad480-9d71-11e9-8ac2-51f10dccc49d.png)

**Note: I have a paid account, not a developers account.** I can access a max of 9900 articles only when let's say the number of articles related to money laundering is 50K. How can I access the remaining articles?

**Comment by mattlisiv** [comment]
Hi @Deadshot20,

While this is a wrapper for News API, this library is not official and I have no real affiliation with News API. Therefore, I can't comment on rates or limits related to types of accounts. I suggest you contact support@newsapi.org .

Personally, when using the API, I use more specific queries in order to have a limited result set.

Best of luck
